### ISSUE TITLE
my file provider

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [MuntashirAkon/unapkm-android#3]
hi , when do open with (?) not apps in list ,

**Comment by MuntashirAkon** [comment]
Currently, you can only open APKM file using your file manager. Open your favourite file manager, select an APKM file and open it with an app entry called **UnApkm**. At this point, it will request you a saving location. Once you do it, it'll start the conversion.

**Comment by Disqu3-mirOir-qt** [comment]
i do exactly this but my file provider not purpose open .apkm with unApkm

**Comment by MuntashirAkon** [comment]
Which file manager do you use? FX?

**Comment by Disqu3-mirOir-qt** [comment]
no i use this
 https://f-droid.org/repo/com.simplemobiletools.filemanager.pro

**Comment by MuntashirAkon** [comment]
Interesting this file manager doesn't supply any category.

**Comment by MuntashirAkon** [comment]
Unfortunately, **Simple File Manager** only supports opening activity that is a launcher item. This is should be a bug on their end. You can submit it in their repository here: https://github.com/SimpleMobileTools/Simple-File-Manager/issues

**Comment by jedivulcan** [comment]
I couldn't get it working with FX, Solid Explorer, or Total Commander. It doesn't show up in any "Open as..." target.

**Comment by MuntashirAkon** [comment]
> I couldn't get it working with FX, Solid Explorer, or Total Commander. It doesn't show up in any "Open as..." target.

That's a different issue. I've fixed it already and will be available in the next release.

**Comment by MuntashirAkon** [comment]
Fixed via b80e69b
