### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [MuntashirAkon/unapkm-android#5]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by MuntashirAkon** [comment]
UnAPKM doesn't have any GUI interface other than a simple progress dialog.

**Comment by mondlicht-und-sterne** [comment]
if that's the case, you can close the issue.
